### ISSUE TITLE
PHP and Wordpress Courses to be Completed

### ISSUE THREAD

**Issue by shaybromer28** [shaybromer28/Treehouse#2]
## TODO

_PHP and Wordpress Training Courses_
- [ ] PHP for Wordpress
- [ ] Wordpress Theme Development
- [ ] Build a Basic PHP Website
- [ ] Using PHP with MySQL
